"""Embed the `tbls doc` output into README.md as a single collapsed section.

`tbls doc` writes one markdown file per table plus an index that links to them
with relative `*.md` links. Those links are meaningless once the text lives in
README.md, so this script concatenates the whole set into one document:
headings are demoted to fit under README's `## Schema`, and the index links are
rewritten to in-page anchors.

Run it through `mise run tbls`, which builds the schema-only database and calls
`tbls doc` first.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
DOC_DIR = ROOT / ".tbls-doc"

START = "<!-- tbls:start -->"
END = "<!-- tbls:end -->"
SUMMARY = "Database schema (generated by <code>tbls doc</code>)"

# The generated block is machine-written, so hold it to a different standard
# than the hand-written prose around it: long table rows (md013), one `Columns`
# heading per table (md024) and the `<details>` wrapper (md033) are all
# deliberate. `disable-num-lines` keeps the exemption scoped to the block.
PYML_RULES = "md013,md024,md033"

FOOTER_RE = re.compile(r"\n*---\n+> Generated by \[tbls\]\([^)]*\)\s*\Z")
LINK_RE = re.compile(r"\[([^\]]+)\]\((?!https?://)([^)]+)\.md\)")
FENCE_RE = re.compile(r"^\s*(?:```|~~~)")


def strip_footer(text: str) -> str:
    """Drop the trailing "Generated by tbls" credit from a generated file."""
    return FOOTER_RE.sub("", text.strip())


def demote(text: str, levels: int) -> str:
    """Push every ATX heading in `text` down by `levels`, skipping code fences."""
    lines: list[str] = []
    in_fence = False
    for line in text.splitlines():
        if FENCE_RE.match(line):
            in_fence = not in_fence
        elif not in_fence and line.startswith("#"):
            line = "#" * levels + line  # noqa: PLW2901
        lines.append(line)
    return "\n".join(lines)


def anchor(stem: str) -> str:
    """GitHub's anchor for a heading whose text is the table name `stem`."""
    return "#" + re.sub(r"[^\w-]", "", stem.lower().replace(" ", "-"))


def relink(text: str) -> str:
    """Point every cross-document `*.md` link at the matching in-page heading."""
    return LINK_RE.sub(lambda m: f"[{m.group(1)}]({anchor(m.group(2))})", text)


def build_section() -> str:
    """Concatenate the generated docs into one anchor-linked markdown section."""
    index = strip_footer((DOC_DIR / "README.md").read_text(encoding="utf-8"))

    # Table order comes from the index, so the body follows the same order as
    # the table list a reader just scrolled past.
    stems = [m.group(2) for m in LINK_RE.finditer(index)]
    # The index's `# <db name>` title is redundant under README's own heading.
    index = re.sub(r"\A#[^#].*\n+", "", index)

    parts = [demote(relink(index), 1)]
    for stem in stems:
        path = DOC_DIR / f"{stem}.md"
        if not path.is_file():
            msg = f"{path} is missing — did `tbls doc` fail?"
            raise SystemExit(msg)
        parts.append(demote(relink(strip_footer(path.read_text(encoding="utf-8"))), 2))
    return "\n\n".join(parts)


def build_block() -> str:
    """Wrap the section in the `<details>` element and the pymarkdown pragma."""
    body = f"<details>\n<summary>{SUMMARY}</summary>\n\n{build_section()}\n\n</details>"
    # The pragma covers every line it precedes, itself excluded.
    return f"<!-- pyml disable-num-lines {len(body.splitlines())} {PYML_RULES} -->\n{body}"


def main() -> int:
    """Rewrite the marked region of README.md, reporting whether it changed."""
    readme = README.read_text(encoding="utf-8")
    region = re.compile(
        rf"(?P<start>^{re.escape(START)}$\n).*?(?P<end>^{re.escape(END)}$)",
        re.DOTALL | re.MULTILINE,
    )
    if not region.search(readme):
        msg = f"{README} has no {START} / {END} markers to fill"
        raise SystemExit(msg)

    updated = region.sub(lambda m: m.group("start") + build_block() + "\n" + m.group("end"), readme)
    if updated == readme:
        print(f"{README.name} is up to date")
        return 0
    README.write_text(updated, encoding="utf-8")
    print(f"{README.name} updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
